### ISSUE TITLE
Joint Mendeley group thing?

### ISSUE THREAD

**Issue by drvinceknight** [sluenenglish/Data-Mining-Review#19]

**Comment by sluenenglish** [comment]
Just created a group and added you both

**Comment by drvinceknight** [comment]
I would suggest calling the group something generic for your PhD. Have
joined, not a problem if you can't change the name etc...

**Comment by sluenenglish** [comment]
Name is now: 'PhD Literature'

**Comment by drvinceknight** [comment]
Add SLE to that please.

Vince

**Comment by sluenenglish** [comment]
Done :+1:
