### ISSUE TITLE
Possibly adopt this structural convention

### ISSUE THREAD

**Issue by drvinceknight** [sluenenglish/Data-Mining-Review#4]
Stumbled upon this: https://github.com/uwescience/shablona

**Comment by sluenenglish** [comment]
This looks good, I'll try to stick to this when I start coding

**Comment by drvinceknight** [comment]
And writing as well. I seem to remember it had a manuscript part in there
no?

**Comment by sluenenglish** [comment]
Do you mean the documentation? I can't see a manuscript part

**Comment by drvinceknight** [comment]
Ah my bad.

I'd add a manuscript directory if I were you and stick to the nice
convention.

V
